apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubectl-pod-rb
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubectl-pod-role
subjects:
- kind: ServiceAccount
  name: kubectl-pod-sa
  namespace: default

