
from debian

RUN apt-get update \
 && apt-get install --assume-yes --no-install-recommends \
      python3 \
      python3-pip \
      python3-rpi.gpio \
 && rm -rf /var/lib/apt/lists/* \
 && pip3 install blinkt \
 && install -d -o root -g root -m 0755 /src

COPY --chown=root:root reset.py /src/

WORKDIR /src

VOLUME ["/src"]

ENTRYPOINT ["/usr/bin/python3"]

CMD ["reset.py"]


