---
- name: Running Worker Node Playbook
  hosts: worker
  gather_facts: no
  become: yes
  become_method: sudo
  tasks:
    - name: Test for raspberry pi /proc/cpuinfo
      command: grep -E "Raspberry Pi|BCM2708|BCM2709|BCM2835|BCM2836" /proc/cpuinfo
      register: grep_cpuinfo_raspberrypi
      failed_when: false
      changed_when: false

    - name: Activating cgroup support
      lineinfile:
        path: /boot/cmdline.txt
        regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
        line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
        backrefs: true
      notify: reboot

    - name: "Install git"
      shell: sudo apt-get -y install git
      args:
        creates: /usr/bin/git

    - name: "Install buildah"
      shell: sudo apt-get -y install buildah
      args:
        creates: /usr/bin/buildah

    - name: "Install k3s"
      shell: "{{ hostvars['transfer_variable']['k8s_join_command'] }} "
      args:
        creates: /usr/local/bin/kubectl

    - name: "Install buildah"
      shell: sudo mkdir /etc/rancher/k3s/
      args:
        creates: /etc/rancher/k3s

    - name: "Push Internal kubeconfig file"
      ansible.builtin.copy:
        src: files/internal.kubeconfig
        dest: /etc/rancher/k3s/k3s.yaml
        mode: '744'

    - name: "Add config file to .bash_profile"
      become_user: pi
      shell: echo "export KUBECONFIG=/etc/rancher/k3s/k3s.yaml" > ~/.bash_profile

    - name: "Install k9s"
      shell: |
        sudo curl -sS https://webi.sh/k9s | sh -
        sudo cp ~/.local/opt/k9s-v0.26.5/bin/k9s /usr/bin/k9s
      args:
        creates: /usr/bin/k9s


  handlers:
    - name: Restart apache
      ansible.builtin.service:
        name: httpd
        state: restarted

    - name: reboot
      reboot:
