apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  index.html.template: |
    <h1>Nginx Pod Info</h1>
    <p>Worker Node Name : NODE_NAME</p>
    <p>Unique Pod Name  : POD_HOSTNAME</p>
  nginx.conf: |
    server {
      listen 80;
      server_name localhost;
      location / {
        root /usr/share/nginx/html;
        index index.html;
      }
    }

